name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test
      - name: Check code coverage
        run: |
          # Parse coverage report and extract coverage percentage
          coverage=$(npx jest --coverageReporters=json-summary | jq -r '.total.lines.pct')
          # Compare coverage against threshold
          if (( $(echo "$coverage >= 80" | bc -l) )); then
            echo "Coverage is above 80% ($coverage%)"
            exit 0
          else
            echo "Coverage is below 80% ($coverage%)"
            exit 1
          fi